from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
import os

from database import SessionLocal, Report


def generate_appointment_report(
    user_id,
    disease_type,
    prediction,
    confidence,
    patient_voice_text,
    image_path
):

    report_folder = "storage/appointment_reports"
    os.makedirs(report_folder, exist_ok=True)

    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join(report_folder, filename)

    c = canvas.Canvas(file_path, pagesize=letter)

    width, height = letter

    c.setFont("Helvetica-Bold", 18)
    c.drawString(180, height - 50, "AI Medical Pre-Consultation Report")

    y = height - 100
    c.setFont("Helvetica", 12)

    c.drawString(50, y, f"Disease Category: {disease_type}")
    y -= 25

    c.drawString(50, y, f"AI Prediction: {prediction}")
    y -= 25

    c.drawString(50, y, f"Model Confidence: {confidence:.2f}")
    y -= 40

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Patient Problem Description (Voice Transcription):")
    y -= 25

    c.setFont("Helvetica", 12)

    text_object = c.beginText(50, y)
    text_object.textLines(patient_voice_text)
    c.drawText(text_object)

    y -= 120

    if image_path and os.path.exists(image_path):

        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Uploaded Medical Image:")
        y -= 20

        c.drawImage(
            image_path,
            50,
            y - 200,
            width=300,
            height=200,
            preserveAspectRatio=True
        )

    c.setFont("Helvetica", 10)
    c.drawString(
        50,
        40,
        f"Generated by AI Clinical Prioritization System | {datetime.now()}"
    )

    c.save()

    # -------------------------
    # SAVE REPORT TO DATABASE
    # -------------------------
    session = SessionLocal()

    report = Report(
        user_id=user_id,
        file_path=file_path
    )

    session.add(report)
    session.commit()
    session.close()

    return file_path